### ISSUE TITLE
In mobile the slides in carousel move a bit horizontally even when scrolling up or down.

### ISSUE THREAD

**Issue by SatyamKr07** [xiaolin/react-image-gallery#616]
**Describe the bug**
When we touch any slide in the carousel, the slide moves a bit horizontally even when scrolling up or down in mobile device. (Bad for ux in mobile devices. This is really annoying if we have a list of posts like in Instagram and we scroll up or down)

**To Reproduce**
1. Go to https://www.linxtion.com/demo/react-image-gallery/
2. Touch the slide in carousel ( or preview carousel just below it)
3. Scroll down or up
4. See the horizontal movement or slide in the carousel.

**Expected behavior**
The slides in the carousel should not move when scrolling up or down as it leads to bad user experience.

**Smartphone (please complete the following information):**
 - Device: Realme 2 pro
 - OS: Android 10
 - Browser : chrome

Please fix this...as this is really a great package and would love to use it in my startup.

**Comment by xiaolin** [comment]
Thanks for reporting.

Fixed in `1.2.6` https://github.com/xiaolin/react-image-gallery/releases/tag/v1.2.6

**Comment by SatyamKr07** [comment]
Really appreciate you quick fix!
But the same issue is still there if we have thumbnails enabled. Please improve swipe gesture for thumbnails also. Thanks

**Comment by xiaolin** [comment]
I see, can you open a new issue for thumbnail swipe fix. Should be quick as the logic will be similar to the current slide fix.

**Comment by SatyamKr07** [comment]
Yeah sure!
